name: "evo-ecom-webaap"

on: workflow_dispatch

jobs: 
  terraforn_init_plan:
    runs-on: Self-Hosted-Runner
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
    
          

